# services:
#   containerssh:
#     image: containerssh/containerssh:v0.5.0
#     container_name: containerssh
#     restart: unless-stopped
#     ports:
#       - "2222:2222"
#     volumes:
#       - ./config.yaml:/etc/containerssh/config.yaml:ro
#       - ./host.key:/var/secrets/host.key:ro
#       - /var/run/docker.sock:/var/run/docker.sock
#     # networks:
#     #   - attack_playground_net
#     depends_on:
#       - auth-config

#   auth-config:
#     image: containerssh/containerssh-test-authconfig:latest
#     container_name: auth-config
#     restart: unless-stopped
#     # networks:
#     #   - attack_playground_net
#     environment:
#       - CONTAINERSSH_ALLOW_ALL=true

# # networks:
# #   attack_playground_net:
# #     name: attack_playground_net
# #     driver: bridge
# #     ipam:
# #       config:
# #         - subnet: 172.21.0.0/16



services:
  containerssh:
    image: containerssh/containerssh:latest
    container_name: containerssh
    restart: unless-stopped
    user: root
    # user: "${CURRENT_UID:?Error: CURRENT_UID is not set. Run ./generate-env.sh first.}:${DOCKER_GID:?Error: DOCKER_GID is not set. Run ./generate-env.sh first.}"
    ports:
      - "2222:2222"
    volumes:
      - ./config.yaml:/etc/containerssh/config.yaml:ro
      - ./host.key:/etc/containerssh/host.key:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - containerssh_net

  containerssh-auth:
    image: python:3.11-slim
    restart: unless-stopped
    command: python /app/auth_server.py
    volumes:
      - ./auth_server.py:/app/auth_server.py:ro
    ports:
      - "2223:8080"
    networks:
      - containerssh_net

networks:
  containerssh_net:
    driver: bridge
